[package]
name = "ch02"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
reqwest = { version = "0.12.22", features = ["stream"] }
tokio = { version = "1.47.1", features = ["full"] }
futures-util = "0.3"
